version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/dev/Dockerfile
    env_file:
      - ./docker/server/dev/common.env
      - ./docker/db/dev/common.env
    ports:
      - "3000:3000"
      - 8888:8888
    volumes:
      - ./app:/app

  db:
    image: postgres:12.1-alpine
    env_file:
      - ./docker/db/dev/common.env
    ports:
      - 5432:5432
    volumes:
      - ./temp/dev/db-data:/var/lib/postgresql/data