version: '3'

services:
  server-prod:
    build:
      context: .
      dockerfile: ./docker/server/prod/Dockerfile
    env_file:
      - ./docker/server/prod/common.env
      - ./docker/db/prod/common.env
    ports:
      - '3000:3000'
      - 8888:8888
    volumes:
      - ./app:/app

  db-prod:
    image: postgres:12.1-alpine
    env_file:
      - ./docker/db/prod/common.env
    ports:
      - 5432:5432
    volumes:
      - ./temp/prod/db-data:/var/lib/postgresql/data
